### ISSUE TITLE
Private key isn't private

### ISSUE THREAD

**Issue by bbqsrc** [clockworkpi/apt#1]
This might be a mistake.

**Comment by cuu** [comment]
ok
The start idea is to let other people can sign their deb with the CPI key like I am doing
but I am not very familiar with deb, if someone try to make a PR with his custom deb to here, will it be ok if he uses his own key to sign the deb?

**Comment by Irmin** [comment]
It's absolutely a mistake. By making the private key you use to sign the Release file public, you subvert [secure apt](https://wiki.debian.org/SecureApt), introducing a huge security hole in the system of anyone who adds your repo to their sources.list and exposing them to man-in-the-middle attacks where, for example, an attacker with a malicious wi-fi access point could spoof your repo and install anything they want because apt thinks it's been signed by you.

You need to generate a new key pair, keep the private key *private* (it's in the name 😉) and sign the repo with that. If you want people to be able to submit packages for inclusion in your repo, that's fine, but they can't be the one to sign the repository that you maintain. You have to do that yourself when you add the packages.

**Comment by reidrankin** [comment]
To your specific concern -- which is admirable -- there's nothing that requires that people use signed .deb packages if they don't want to, or keeping them from making their own keys and using those instead.

**Comment by cuu** [comment]
thanks to all reply 
the KEY.gpg is updated and private key is stored in private
closed
