### ISSUE TITLE
Legacy key format

### ISSUE THREAD

**Issue by andypiper** [clockworkpi/apt#2]
Running `apt update` on DevTerm R01 results in various messages, and ends with a message about apt key being deprecated.

`W: https://raw.githubusercontent.com/clockworkpi/apt/main/debian/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`

Running `apt-key list`:

`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).`

**Comment by thomasdstewart** [comment]
Not sure the repo can fix this, as it really needs fixing on each system. Probably an update to the README.md to help with this giving instructions along the lines of instead of doing: "wget -O - https://raw.githubusercontent.com/clockworkpi/apt/main/debian/KEY.gpg | sudo apt-key add - " which has not been correct for many years, something like this is better: curl https://raw.githubusercontent.com/clockworkpi/apt/main/debian/KEY.gpg > /etc/apt/trusted.gpg.d/clockworkpi.asc

**Comment by andypiper** [comment]
Fair point. Can change in the wiki instructions... https://github.com/clockworkpi/DevTerm/wiki/Create-DevTerm-R01-OS-image-from-scratch

**Comment by cuu** [comment]
> Fair point. Can change in the wiki instructions... https://github.com/clockworkpi/DevTerm/wiki/Create-DevTerm-R01-OS-image-from-scratch

done
